### ISSUE TITLE
Project Status Question

### ISSUE THREAD

**Issue by steowens** [svenefftinge/xtendfx#12]
Is this still an active project?

**Comment by svenefftinge** [comment]
Hi Steven, no it is not actively maintained.
But OTOH it doesn't contain a whole lot of code, so if you are interested in using it, you could just for fork it and maintain it yourself.

**Comment by JanKoehnlein** [comment]
Also note that some parts/ideas of it have been picked up by FXDiagram (active annotation @FxProperty, operators for Properties).
http://jankoehnlein.github.io/FXDiagram/

**Comment by pacher** [comment]
@svenefftinge It is promoted on the main page of http://xtend-lang.org as a feature of xtend, kind of... But if somebody will check it out, she will get a broken project. Isn't it embarrassing to have something broken on the front page? Just a little fix in pom.xml will do the job, yet my pull request from 2014 is still hanging...
I am just saying, if you refuse even to correct some dependencies in pom.xml, may be you should consider removing it from http://xtend-lang.org?

**Comment by svenefftinge** [comment]
You are right. It should at least work with the latest version.
